//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountingasset
    {
        public int TransactionID { get; set; }
        public int AssetID { get; set; }
        public string AccountNumber { get; set; }
        public int DepreciationPeriod { get; set; }
        public System.DateTime DepreciationDate { get; set; }
        public System.DateTime DateEntryDate { get; set; }
        public decimal StartingValue { get; set; }
        public decimal CurrentValue { get; set; }
        public decimal DepreciationRate { get; set; }
    }
}
