//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class accrec
    {
        public int TransactionID { get; set; }
        public string InvoicedTo { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string ProjectID { get; set; }
        public double InvoiceAmount { get; set; }
        public string ProjectName { get; set; }
        public string OfficeLocation { get; set; }
    }
}
