//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class assetmain
    {
        public int AssetID { get; set; }
        public string AssetPartNumber { get; set; }
        public int AssetTypeID { get; set; }
        public string AssetDescription { get; set; }
        public decimal AssetCost { get; set; }
        public int WarehouseID { get; set; }
        public int EmployeeID { get; set; }
        public bool AssetActive { get; set; }
        public System.DateTime ActiveDate { get; set; }
        public string AssetNotes { get; set; }
        public Nullable<System.DateTime> RetirementDate { get; set; }
        public string RetirementNotes { get; set; }
        public System.DateTime DataEntryDate { get; set; }
    }
}
