//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class bluejayoffice
    {
        public int TransactionID { get; set; }
        public int OfficeID { get; set; }
        public string BusinessAddress { get; set; }
        public string City { get; set; }
        public string BusinessState { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> AreaManagerID { get; set; }
    }
}
