//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class bulktool
    {
        public int TransactionID { get; set; }
        public int EmployeeID { get; set; }
        public int CategoryID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime SignOutDate { get; set; }
        public int SignOutEmployeeID { get; set; }
        public string IssueNotes { get; set; }
        public bool StillAssigned { get; set; }
        public Nullable<System.DateTime> SignInDate { get; set; }
        public Nullable<int> SignInEmployeeID { get; set; }
    }
}
