//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class designprojectsurveyor
    {
        public int TransactionID { get; set; }
        public int ProjectID { get; set; }
        public int SurveyorID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime DateAssigned { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public bool ReWalk { get; set; }
        public string SurveyorNotes { get; set; }
        public string WOVStatus { get; set; }
    }
}
