//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class designproject
    {
        public int TransactionID { get; set; }
        public int ProjectID { get; set; }
        public string ProjectAddress { get; set; }
        public string City { get; set; }
        public int OfficeID { get; set; }
        public System.DateTime DateReceived { get; set; }
        public int JobTypeID { get; set; }
        public decimal SurveyInvoice { get; set; }
        public decimal BJCInvoice { get; set; }
        public string JobStatus { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string Coordinator { get; set; }
        public string ProjectNotes { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> BillingID { get; set; }
    }
}
