//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class designpermit
    {
        public int TransactionID { get; set; }
        public int ProjectID { get; set; }
        public System.DateTime DateReceived { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public int Quantity { get; set; }
        public string PermitStatus { get; set; }
        public int EmployeeID { get; set; }
        public string PermitNotes { get; set; }
        public Nullable<decimal> PermitCost { get; set; }
        public Nullable<decimal> PermitPrice { get; set; }
    }
}
