//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class designpermitimport
    {
        public int TransactionID { get; set; }
        public int ProjectID { get; set; }
        public string CarlID { get; set; }
        public string SurveyType { get; set; }
        public string JobName { get; set; }
        public string FieldEngineer { get; set; }
        public string ConstSupervisor { get; set; }
        public string PermitType { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string PermitAgency { get; set; }
        public Nullable<System.DateTime> PermitSubmitted { get; set; }
        public Nullable<System.DateTime> PermitApproved { get; set; }
        public Nullable<System.DateTime> PermitExpiration { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public Nullable<System.DateTime> PermitClosed { get; set; }
        public string PermitComment { get; set; }
        public Nullable<bool> ProjectActive { get; set; }
        public System.DateTime TransactionDate { get; set; }
    }
}
