//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeovernightwork
    {
        public int TransactionID { get; set; }
        public int DepartmentID { get; set; }
        public int EmployeeID { get; set; }
        public int ManagerID { get; set; }
        public int VehicleID { get; set; }
        public int ProjectID { get; set; }
        public System.DateTime WorkDate { get; set; }
        public string OutTime { get; set; }
        public string WorkLocation { get; set; }
        public string InETA { get; set; }
        public System.DateTime DataEntryDate { get; set; }
        public int OfficeID { get; set; }
    }
}
