//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class itasset
    {
        public int ItemID { get; set; }
        public string Item { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> ItemQuantity { get; set; }
        public Nullable<decimal> ItemValue { get; set; }
        public string Upgrades { get; set; }
        public int WarehouseID { get; set; }
        public Nullable<bool> ActiveItem { get; set; }
        public Nullable<System.DateTime> RetirementDate { get; set; }
        public string RetirementNotes { get; set; }
    }
}
