//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class jsiladderinspection
    {
        public int TransactionID { get; set; }
        public int JSITransactionID { get; set; }
        public string ExtensionLadder { get; set; }
        public string SmallerLadder { get; set; }
        public string DityRaitingStickers { get; set; }
        public string CompanyLaders { get; set; }
        public string LadderRackLocks { get; set; }
    }
}
