//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class jsimain
    {
        public int JSITransactionID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int ProjectID { get; set; }
        public int EmployeeID { get; set; }
        public int DepartmentID { get; set; }
        public int VehicleID { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public int ManagerID { get; set; }
        public int DataEntryEmployeeID { get; set; }
        public int InspectingEmployeeID { get; set; }
    }
}
