//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class jsioverall
    {
        public int TransactionID { get; set; }
        public int JSITransactionID { get; set; }
        public string OverallInspection { get; set; }
        public string SafetyConcerns { get; set; }
        public int InspectingEmployeeID { get; set; }
        public System.DateTime InspectionDate { get; set; }
    }
}
