//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class JSIPPE
    {
        public int TransactionID { get; set; }
        public int JSITransactionID { get; set; }
        public string SafetyVest { get; set; }
        public string SafetyGlassGloves { get; set; }
        public string SafetyFootGear { get; set; }
        public string FallProtection { get; set; }
        public string HardHat { get; set; }
    }
}
