//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class jsivehicle
    {
        public int TransactionID { get; set; }
        public int JSITransactionID { get; set; }
        public bool Magnets { get; set; }
        public bool VehicleCleanlieness { get; set; }
        public bool VehicleSecure { get; set; }
        public bool SafetyMaintenanceIssues { get; set; }
        public bool FireExtinguisherFirstAidKit { get; set; }
        public int VehicleID { get; set; }
    }
}
