//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class letterparagraphhistory
    {
        public int TransactionID { get; set; }
        public int LetterID { get; set; }
        public int ParagraphID { get; set; }
        public int ParagraphNumber { get; set; }
        public string ParagraphText { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
