//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineWarranty
    {
        public int MachineWarrantyID { get; set; }
        public string ServiceTag { get; set; }
        public System.DateTime WarrantyExpiration { get; set; }
        public int MachineID { get; set; }
        public int WarrantyProviderID { get; set; }
    
        public virtual WarrantyProvider WarrantyProvider { get; set; }
    }
}
