//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Machine()
        {
            this.SupportTickets = new HashSet<SupportTicket>();
        }
    
        public int MachineID { get; set; }
        public string Name { get; set; }
        public string GeneralRole { get; set; }
        public string InstalledRoles { get; set; }
        public int OperatingSysID { get; set; }
        public int MachineTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportTicket> SupportTickets { get; set; }
        public virtual MachineType MachineType { get; set; }
        public virtual OperatingSy OperatingSy { get; set; }
    }
}
