//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class masterpartlist
    {
        public int PartID { get; set; }
        public string PartNumber { get; set; }
        public string JDEPartNumber { get; set; }
        public string PartDescription { get; set; }
        public bool Active { get; set; }
        public double Price { get; set; }
    }
}
