//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class productionproject
    {
        public int TransactionID { get; set; }
        public int ProjectID { get; set; }
        public int BusinessLineID { get; set; }
        public string BusinessAddress { get; set; }
        public string City { get; set; }
        public string BusinessState { get; set; }
        public int ProjectManagerID { get; set; }
        public int AssignedOfficeID { get; set; }
        public System.DateTime DateReceived { get; set; }
        public Nullable<System.DateTime> ECDDate { get; set; }
        public int CurrentStatusID { get; set; }
        public string ProjectNotes { get; set; }
    }
}
