//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentaltracking
    {
        public int TransactionID { get; set; }
        public System.DateTime RequestingDate { get; set; }
        public string PONumber { get; set; }
        public int EmployeeID { get; set; }
        public int VendorID { get; set; }
        public System.DateTime PickupDate { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public int NoOfDaysRequested { get; set; }
        public int TotalNoOfDays { get; set; }
        public decimal TotalCost { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int ProjectID { get; set; }
        public decimal ProjectedCost { get; set; }
    }
}
