//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentaltackingitem
    {
        public int TransactionID { get; set; }
        public int RentalTrackingID { get; set; }
        public string RentalPartNo { get; set; }
        public string RentalDescription { get; set; }
        public bool AccessoriesAttached { get; set; }
        public int EmployeeID { get; set; }
        public string ItemNotes { get; set; }
    }
}
