//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class toolinspectionproblem
    {
        public int TransactionID { get; set; }
        public int VehicleID { get; set; }
        public int InspectioID { get; set; }
        public string InspectionType { get; set; }
        public bool ToolsPresent { get; set; }
        public bool ToolsServiceable { get; set; }
        public string InspectionNotes { get; set; }
    }
}
