//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class towmotorengineoff
    {
        public int TransactionID { get; set; }
        public int InspectionID { get; set; }
        public bool TransmissionFluid { get; set; }
        public bool EngineAirCleaner { get; set; }
        public bool FuelSedimentor { get; set; }
        public bool RadiatorCoolant { get; set; }
        public bool OperatorsManual { get; set; }
        public bool InformationPlate { get; set; }
        public bool SeatBelt { get; set; }
        public bool HoodLatch { get; set; }
        public bool BrakeFluid { get; set; }
        public bool OverheadGuard { get; set; }
        public bool FingerGuards { get; set; }
        public bool ParkingBrake { get; set; }
        public bool SteeringOperation { get; set; }
        public bool DriveControl { get; set; }
        public bool TiltControl { get; set; }
        public bool Cab { get; set; }
        public bool FuelLevel { get; set; }
        public bool Temperature { get; set; }
        public bool InstrumentMonitors { get; set; }
    }
}
