//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class towmotormain
    {
        public int TowMotorID { get; set; }
        public string TowMotorNumber { get; set; }
        public int TowMotorYear { get; set; }
        public string TowMotorMake { get; set; }
        public string TowMotorModel { get; set; }
        public string TowMotorSerialNo { get; set; }
        public decimal TowMotorHours { get; set; }
        public int WarehouseID { get; set; }
        public System.DateTime OilChangeDate { get; set; }
        public bool TowMotorActive { get; set; }
    }
}
