//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class towmotorengineon
    {
        public int TransactionID { get; set; }
        public int InspectionID { get; set; }
        public bool Leaks { get; set; }
        public bool Tires { get; set; }
        public bool Forks { get; set; }
        public bool LoadBackrest { get; set; }
        public bool PropaneTank { get; set; }
        public bool SafetyWarning { get; set; }
        public bool Battery { get; set; }
        public bool EngineBelts { get; set; }
        public bool HydraulicFluid { get; set; }
        public bool Accelerator { get; set; }
        public bool ServiceBrake { get; set; }
        public bool HoistLoweringControl { get; set; }
        public bool AttachmentControl { get; set; }
        public bool HornsLight { get; set; }
        public bool Ammeter { get; set; }
        public bool EngineOilPressure { get; set; }
        public bool HourMeter { get; set; }
        public bool EngineOilLevel { get; set; }
    }
}
