//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class towmotorproblem
    {
        public int ProblemID { get; set; }
        public int TowMotorID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public System.DateTime DateReported { get; set; }
        public string ProblemReported { get; set; }
        public string ProblemStatus { get; set; }
        public System.DateTime DateWorkPerformed { get; set; }
        public string WorkedPerformed { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceAmoutn { get; set; }
    }
}
