//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class towmotorasset
    {
        public int TransactionID { get; set; }
        public int InspectionID { get; set; }
        public int SafetyCones { get; set; }
        public int SafetyGlasses { get; set; }
        public int HardHat { get; set; }
        public int FireExtinguisher { get; set; }
    }
}
