//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class trailercable
    {
        public int TransactionID { get; set; }
        public int PartID { get; set; }
        public string PartDescription { get; set; }
        public string CableType { get; set; }
    }
}
