//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicleproblem
    {
        public int ProblemID { get; set; }
        public int VehicleID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Problem { get; set; }
        public double ProblemCost { get; set; }
        public bool ProblemSolved { get; set; }
        public int VendorID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<System.DateTime> ResolutionDate { get; set; }
        public string ProblemResolution { get; set; }
        public string ProblemStatus { get; set; }
    }
}
