//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicleinvoice
    {
        public int InvoiceID { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int VehicleID { get; set; }
        public decimal InvoiceAmount { get; set; }
        public string InvoicePath { get; set; }
        public Nullable<int> VendorID { get; set; }
    }
}
