//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public int VehicleID { get; set; }
        public int BJCNumber { get; set; }
        public int VehicleYear { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string LicensePlate { get; set; }
        public string VINNumber { get; set; }
        public int OilChangeOdometer { get; set; }
        public System.DateTime OilChangeDate { get; set; }
        public int EmployeeID { get; set; }
        public string Notes { get; set; }
        public bool Available { get; set; }
        public bool Active { get; set; }
        public string AssignedOffice { get; set; }
    }
}
