//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicletype
    {
        public int TransactionID { get; set; }
        public string VehicleType1 { get; set; }
        public int FireExtinguiserhs { get; set; }
        public int GasCards { get; set; }
        public int FirstAidKits { get; set; }
        public int Signs { get; set; }
        public int Cones { get; set; }
        public int Ladders { get; set; }
    }
}
