//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicleinfohistory
    {
        public int TransactionID { get; set; }
        public int VehicleInfoID { get; set; }
        public int EmployeeID { get; set; }
        public string FieldChanged { get; set; }
        public string ValueChanged { get; set; }
        public System.DateTime TransactionDate { get; set; }
    }
}
