//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class weeklybulktoolinspection
    {
        public int TransactionID { get; set; }
        public int InspectionID { get; set; }
        public int VehicleID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public bool ToolsPresent { get; set; }
        public string InspectionNotes { get; set; }
        public Nullable<bool> ConesCorrect { get; set; }
        public Nullable<bool> SignsCorrect { get; set; }
        public Nullable<bool> FirstAidCorrect { get; set; }
        public Nullable<bool> FireExtingisher { get; set; }
    }
}
