//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class worktaskstat
    {
        public int TransactionID { get; set; }
        public int WorkTaskID { get; set; }
        public decimal TaskMean { get; set; }
        public decimal TaskVariance { get; set; }
        public decimal TaskSD { get; set; }
        public decimal TaskLimiter { get; set; }
    }
}
