//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class worktask
    {
        public int WorkTaskID { get; set; }
        public string WorkTask1 { get; set; }
        public decimal TaskCost { get; set; }
        public Nullable<bool> TaskActive { get; set; }
        public Nullable<decimal> ProductionValue { get; set; }
    }
}
